module.exports = class Data1774525407603 {
    name = 'Data1774525407603'

    async up(db) {
        await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "address" text NOT NULL, "network" character varying(16) NOT NULL, "name" text NOT NULL, "symbol" text NOT NULL, "decimals" numeric NOT NULL, "price" numeric NOT NULL, "is_pool_token" boolean NOT NULL, "coin_gecko_id" text, "tvl_multiplier" integer NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_40a4dcc6b727285c6539aa1d1c" ON "token" ("address") `)
        await db.query(`CREATE INDEX "IDX_b1c1e33dcc0f808971cf0540d8" ON "token" ("network") `)
        await db.query(`CREATE INDEX "IDX_e31c0ee2b8847dc76f3646ecc7" ON "token" ("symbol") `)
        await db.query(`CREATE TABLE "port_vault" ("id" character varying NOT NULL, "address" text NOT NULL, "type" character varying(8) NOT NULL, "started_at" numeric NOT NULL, "network" character varying(16) NOT NULL, "symbol" text NOT NULL, "decimals" integer NOT NULL, "name" text NOT NULL, "management_fee" numeric NOT NULL, "current_nav" numeric NOT NULL, "apy" numeric NOT NULL, "tvl" numeric NOT NULL, "avg7d_apy" numeric NOT NULL, "avg30d_apy" numeric NOT NULL, "avg1y_apy" numeric NOT NULL, "risk_level" integer NOT NULL, "deposit_cap" numeric NOT NULL, "total_withdrawal_requests_in_base_token" numeric NOT NULL, "total_pending_withdrawal_requests" numeric NOT NULL, "total_activity" numeric NOT NULL, "status" character varying(6) NOT NULL, "assets" text array NOT NULL, "teller" text NOT NULL, "accountant" text NOT NULL, "atomic_queue" text NOT NULL, "atomic_solver" text NOT NULL, "roles_authority" text NOT NULL, "manager" text NOT NULL, "funds_diverted" numeric NOT NULL, "base_token_id" character varying, CONSTRAINT "PK_08f53fed84f43a7ebb20c27e7a4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_981890e7e8876416d00d330b13" ON "port_vault" ("address") `)
        await db.query(`CREATE INDEX "IDX_af4e487a8df3021fcdbce98f08" ON "port_vault" ("base_token_id") `)
        await db.query(`CREATE TABLE "port_withdrawal_request" ("id" character varying NOT NULL, "status" character varying(9) NOT NULL, "want_amount" numeric NOT NULL, "offer_amount" numeric NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "block" numeric NOT NULL, "deadline" numeric NOT NULL, "vault_id" character varying, "user_id" character varying, "want_token_id" character varying, CONSTRAINT "PK_ed915cc61359c8d891a55ba2f4b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ffc5d7d8ae2d3710c768b4ee4b" ON "port_withdrawal_request" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_e669b50286dda06958d2c860a9" ON "port_withdrawal_request" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_68b6f1d4b96f2d84200cac48d1" ON "port_withdrawal_request" ("status") `)
        await db.query(`CREATE INDEX "IDX_e4661991fc8d871c22a29fd3cb" ON "port_withdrawal_request" ("want_token_id") `)
        await db.query(`CREATE TABLE "port_deposit" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "shares" numeric NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "block" numeric NOT NULL, "vault_id" character varying, "user_id" character varying, "asset_id" character varying, CONSTRAINT "PK_d148c084bedb8495a61add4819d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f32f083592626a10515f34cb5a" ON "port_deposit" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_f63dd6895d5c954fe797fda674" ON "port_deposit" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_ce5906346ec55f7708ea2f06f3" ON "port_deposit" ("asset_id") `)
        await db.query(`CREATE TABLE "nara_redemption_activity" ("id" character varying NOT NULL, "action" character varying(14) NOT NULL, "nara_usd_amount" numeric NOT NULL, "collateral_amount" numeric, "collateral_asset_address" text NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "block" numeric NOT NULL, "redemption_id" character varying, CONSTRAINT "PK_449dddca9a529586c5321f41805" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a9c29e022e8df6ea4b5db13250" ON "nara_redemption_activity" ("redemption_id") `)
        await db.query(`CREATE INDEX "IDX_fd4e1ddb2b0368ba16662243b4" ON "nara_redemption_activity" ("action") `)
        await db.query(`CREATE INDEX "IDX_ac22e44a76a1ce576cc4975b22" ON "nara_redemption_activity" ("collateral_asset_address") `)
        await db.query(`CREATE INDEX "IDX_380f801a670e857ab75cec5bd6" ON "nara_redemption_activity" ("tx_hash") `)
        await db.query(`CREATE TABLE "nara_redemption" ("id" character varying NOT NULL, "status" character varying(9) NOT NULL, "nara_usd_amount" numeric NOT NULL, "collateral_amount" numeric, "collateral_asset_address" text NOT NULL, "requested_at" numeric NOT NULL, "completed_at" numeric, "updated_at" numeric NOT NULL, "user_id" character varying, CONSTRAINT "PK_ff6df1add38d0cdf01e436399a4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1323be9f9ee12a82d884006074" ON "nara_redemption" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_cc3976bd4ca46d3f94248749bd" ON "nara_redemption" ("status") `)
        await db.query(`CREATE INDEX "IDX_27a5f8bb0ac57cd1868e5dddd0" ON "nara_redemption" ("collateral_asset_address") `)
        await db.query(`CREATE TABLE "user" ("id" character varying NOT NULL, "address" text NOT NULL, "is_testnet" boolean NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3122b4b8709577da50e89b6898" ON "user" ("address") `)
        await db.query(`CREATE TABLE "nara_global_stats" ("id" character varying NOT NULL, "network" character varying(16) NOT NULL, "nara_usd_supply" numeric NOT NULL, "nara_usd_supply_formatted" numeric NOT NULL, "nara_usd_decimals" integer NOT NULL, "reserve_fund_formatted" numeric NOT NULL, "protocol_backing_ratio" numeric NOT NULL, "percentage_staked" numeric NOT NULL, "investment_assets_formatted" numeric NOT NULL, "cash_and_equivalents_formatted" numeric NOT NULL, "total_assets_formatted" numeric NOT NULL, "apy7d" numeric NOT NULL, "apy14d" numeric NOT NULL, "apy30d" numeric NOT NULL, "weighted_apy7d" numeric NOT NULL, "weighted_tenor_days" integer, "updated_at" numeric NOT NULL, CONSTRAINT "PK_ca6437959632f20249ff22d3050" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_49add277f5c2a04994682fe6bc" ON "nara_global_stats" ("network") `)
        await db.query(`CREATE TABLE "nara_supply_chart_point" ("id" character varying NOT NULL, "network" character varying(16) NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "nara_usd_supply" numeric NOT NULL, "nara_usd_supply_formatted" numeric NOT NULL, CONSTRAINT "PK_63da7b0b67d4e53729146d5a089" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1cfd9f5fb99a6c2c36c24c1de0" ON "nara_supply_chart_point" ("network") `)
        await db.query(`CREATE INDEX "IDX_b1fbcf17de84907b8550cb9d74" ON "nara_supply_chart_point" ("timestamp") `)
        await db.query(`CREATE TABLE "nara_tvl_chart_point" ("id" character varying NOT NULL, "network" character varying(16) NOT NULL, "chain" text NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "tvl_usd" numeric NOT NULL, CONSTRAINT "PK_b939a3b5a673a1c61fae48694b5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e9a05a0bc52b6244ecd9c4e909" ON "nara_tvl_chart_point" ("network") `)
        await db.query(`CREATE INDEX "IDX_cf3e74235a27cda9498071f39b" ON "nara_tvl_chart_point" ("chain") `)
        await db.query(`CREATE INDEX "IDX_2bad7d295eae01d163f98acf1f" ON "nara_tvl_chart_point" ("timestamp") `)
        await db.query(`CREATE TABLE "nara_apy_chart_point" ("id" character varying NOT NULL, "network" character varying(16) NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "updated_at" numeric NOT NULL, "exchange_rate" numeric NOT NULL, "apr" numeric NOT NULL, "apy7d" numeric NOT NULL, "apy14d" numeric NOT NULL, "apy30d" numeric NOT NULL, CONSTRAINT "PK_5ec62d975c6158d60228ef3ad8c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7d48d7547ad17620d0adcdb0f4" ON "nara_apy_chart_point" ("network") `)
        await db.query(`CREATE INDEX "IDX_6c9dc0e906a792145f68a710e3" ON "nara_apy_chart_point" ("timestamp") `)
        await db.query(`CREATE TABLE "total_requested_amount" ("id" character varying NOT NULL, "collateral_address" text NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_d71476809bf7fc796c6c398b1a0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_39e056ef1c3652021a6ed6988b" ON "total_requested_amount" ("collateral_address") `)
        await db.query(`CREATE TABLE "port_global_stats" ("id" character varying NOT NULL, "network" character varying(16) NOT NULL, "active_users" numeric NOT NULL, CONSTRAINT "PK_5fe9a9ee7840f3d8ec440386874" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d47d6e1f236c286246682d21e9" ON "port_global_stats" ("network") `)
        await db.query(`CREATE TABLE "port_nav_update" ("id" character varying NOT NULL, "old_rate" numeric NOT NULL, "new_rate" numeric NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "block" numeric NOT NULL, "vault_id" character varying, CONSTRAINT "PK_ec1d017c5257f7d54b2e6929c89" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_47f489d5d233c0aeae12d2f8d6" ON "port_nav_update" ("vault_id") `)
        await db.query(`CREATE TABLE "port_vault_status_update" ("id" character varying NOT NULL, "new_status" character varying(6) NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "block" numeric NOT NULL, "vault_id" character varying, CONSTRAINT "PK_c70e1facec40eaa61fb42737629" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4c9343dbb0386a2fd79a60a5be" ON "port_vault_status_update" ("vault_id") `)
        await db.query(`CREATE TABLE "port_request_fulfilled" ("id" character varying NOT NULL, "offer_amount_spent" numeric NOT NULL, "want_amount_received" numeric NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "block" numeric NOT NULL, "vault_id" character varying, "user_id" character varying, "want_token_id" character varying, CONSTRAINT "PK_de477144e16d67a93a5781189f0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_69e031e6972e23e8fd9823e318" ON "port_request_fulfilled" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_8f55ac51781c6ff117f55673c7" ON "port_request_fulfilled" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_7724bff57c4be6c38135200883" ON "port_request_fulfilled" ("want_token_id") `)
        await db.query(`CREATE TABLE "port_vault_activity" ("id" character varying NOT NULL, "action" character varying(28) NOT NULL, "details" text NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "vault_id" character varying, CONSTRAINT "PK_08b9fad2996ef9e667b1c185368" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_dd39c6dd9ddb312e0a164fb974" ON "port_vault_activity" ("vault_id") `)
        await db.query(`CREATE TABLE "port_vault_transaction_history" ("id" character varying NOT NULL, "action" character varying(28) NOT NULL, "amount" numeric NOT NULL, "asset" text NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "vault_id" character varying, "user_id" character varying, CONSTRAINT "PK_c068ad4c14eb7027595438bb538" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_368b5d2673663117cb85534a75" ON "port_vault_transaction_history" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_6c430ee33ebf67f6b6d58ddfa5" ON "port_vault_transaction_history" ("user_id") `)
        await db.query(`CREATE TABLE "port_vault_apy" ("id" character varying NOT NULL, "apy" numeric NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "vault_id" character varying, CONSTRAINT "PK_38d72c6773321e80607bfbccd7b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f957e82b58c244c4f23fdf2590" ON "port_vault_apy" ("vault_id") `)
        await db.query(`CREATE TABLE "port_vault_apy_chart" ("id" character varying NOT NULL, "apy7d" numeric NOT NULL, "apy14d" numeric NOT NULL, "apy30d" numeric NOT NULL, "apy365d" numeric NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "exchange_rate" numeric NOT NULL, "exchange_rate7d_ago" numeric NOT NULL, "exchange_rate14d_ago" numeric NOT NULL, "exchange_rate30d_ago" numeric NOT NULL, "exchange_rate365d_ago" numeric NOT NULL, "vault_id" character varying, CONSTRAINT "PK_b458e2302536cd5ad08bd33be40" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ead1b71dee7261317832feb1ee" ON "port_vault_apy_chart" ("vault_id") `)
        await db.query(`CREATE TABLE "funds_diverted" ("id" character varying NOT NULL, "strategy" text NOT NULL, "amount" numeric NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "vault_id" character varying, CONSTRAINT "PK_34b0b4d7b2d8cc140dcf3a1ddf3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c5eaa6b419c6158d79befc5f38" ON "funds_diverted" ("vault_id") `)
        await db.query(`CREATE TABLE "funds_reverted" ("id" character varying NOT NULL, "strategy" text NOT NULL, "amount" numeric NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "vault_id" character varying, CONSTRAINT "PK_867f31a289fa2cd25ec8c7e3fdf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_50cb90c60da3d340d244b1033a" ON "funds_reverted" ("vault_id") `)
        await db.query(`CREATE TABLE "expected_exchange_rate" ("id" character varying NOT NULL, "expected_last_accrual_ts" integer NOT NULL, "expected_last_update_ts" integer NOT NULL, "expected_assets_base_raw" numeric NOT NULL, "expected_borrowed_base_raw" numeric NOT NULL, "expected_borrowed_principal_base_raw" numeric NOT NULL, "expected_exchange_rate_base_raw" numeric NOT NULL, "commitment_fee_accrued_mtd_base_raw" numeric NOT NULL, "commitment_fee_projected_month_end_base_raw" numeric NOT NULL, "commitment_fee_mtd_month_start_ts" integer NOT NULL, "borrow_interest_accrued_mtd_base_raw" numeric NOT NULL, "borrow_interest_projected_month_end_base_raw" numeric NOT NULL, "borrow_interest_mtd_month_start_ts" integer NOT NULL, "expected_repayment_pending_base_raw" numeric NOT NULL, "expected_repayment_credit_base_raw" numeric NOT NULL, "borrow_rate_bps" numeric NOT NULL, "commitment_fee_rate_bps" numeric NOT NULL, "total_shares_tracked" numeric NOT NULL, "total_shares_source" text NOT NULL, "net_assets_tracked_base_raw" numeric NOT NULL, "idle_base_tracked" numeric NOT NULL, "invested_base_tracked" numeric NOT NULL, "accrued_commitment_fee_base" numeric NOT NULL, "accrued_borrow_interest_base" numeric NOT NULL, "last_accrual_block" numeric NOT NULL, "strategy_yield_base" numeric NOT NULL, "last_snapshot_ts_used" integer NOT NULL, "commit_fee_remainder_numerator" numeric NOT NULL, "borrow_interest_remainder_numerator" numeric NOT NULL, "vault_id" character varying, CONSTRAINT "PK_a2abdd110451445620d5c35dfa9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f05d1bb98338c38d52a9803864" ON "expected_exchange_rate" ("vault_id") `)
        await db.query(`CREATE TABLE "expected_exchange_rate_snapshot" ("id" character varying NOT NULL, "network" character varying(16) NOT NULL, "vault_address" text NOT NULL, "block_height" numeric NOT NULL, "block_timestamp_ms" numeric NOT NULL, "now_sec" integer NOT NULL, "update_ts" integer NOT NULL, "block" numeric NOT NULL, "block_timestamp" integer NOT NULL, "expected_last_accrual_ts" integer NOT NULL, "expected_last_update_ts" integer NOT NULL, "expected_assets_base_raw" numeric NOT NULL, "expected_borrowed_base_raw" numeric NOT NULL, "expected_borrowed_principal_base_raw" numeric NOT NULL, "expected_exchange_rate_base_raw" numeric NOT NULL, "commitment_fee_accrued_mtd_base_raw" numeric NOT NULL, "commitment_fee_projected_month_end_base_raw" numeric NOT NULL, "commitment_fee_mtd_month_start_ts" integer NOT NULL, "borrow_interest_accrued_mtd_base_raw" numeric NOT NULL, "borrow_interest_projected_month_end_base_raw" numeric NOT NULL, "borrow_interest_mtd_month_start_ts" integer NOT NULL, "expected_repayment_pending_base_raw" numeric NOT NULL, "expected_repayment_credit_base_raw" numeric NOT NULL, "borrow_rate_bps" numeric NOT NULL, "commitment_fee_rate_bps" numeric NOT NULL, "total_shares_tracked" numeric NOT NULL, "total_shares_source" text NOT NULL, "net_assets_tracked_base_raw" numeric NOT NULL, "idle_base_tracked" numeric NOT NULL, "invested_base_tracked" numeric NOT NULL, "accrued_commitment_fee_base" numeric NOT NULL, "accrued_borrow_interest_base" numeric NOT NULL, "last_accrual_block" numeric NOT NULL, "utilization_bps" numeric NOT NULL, "idle_base" numeric NOT NULL, "invested_base" numeric NOT NULL, "effective_strategy_value_base" numeric NOT NULL, "borrowed_principal_base" numeric NOT NULL, "borrowed_for_tier" numeric NOT NULL, "borrowed_reported" numeric NOT NULL, "util_for_tier_bps" numeric NOT NULL, "util_reported_bps" numeric NOT NULL, "net_assets_base" numeric NOT NULL, "eer" numeric NOT NULL, "total_assets_base" numeric NOT NULL, "dt_seconds" integer NOT NULL, "commitment_fee_accrued_delta_base" numeric NOT NULL, "borrow_interest_accrued_delta_base" numeric NOT NULL, "util_for_tier_bps_start" numeric NOT NULL, "commit_fee_rate_bps_start" numeric NOT NULL, "batch_first_block" numeric NOT NULL, "batch_last_block" numeric NOT NULL, "batch_count" integer NOT NULL, "hour_ts" integer NOT NULL, "last_accrual_ts_before" integer NOT NULL, "last_accrual_ts_after" integer NOT NULL, "util_bps_end" numeric NOT NULL, "vault_id" character varying, CONSTRAINT "PK_572bd86147c3632857dbe8c7cc0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7d4893109abde7ce94552a1e22" ON "expected_exchange_rate_snapshot" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_bddedd85f23f7d4251db99ba7d" ON "expected_exchange_rate_snapshot" ("network") `)
        await db.query(`CREATE INDEX "IDX_5dacf548b21859742ddf18b6b2" ON "expected_exchange_rate_snapshot" ("vault_address") `)
        await db.query(`CREATE INDEX "IDX_4a29723480fdc001f735b1a0ed" ON "expected_exchange_rate_snapshot" ("block_height") `)
        await db.query(`CREATE INDEX "IDX_fb7ae07e1c46f9d74252682dec" ON "expected_exchange_rate_snapshot" ("update_ts") `)
        await db.query(`CREATE TABLE "manager_withdraw" ("id" character varying NOT NULL, "vault_address" text NOT NULL, "borrower" text NOT NULL, "token" text NOT NULL, "amount_raw" numeric NOT NULL, "token_decimals" integer NOT NULL, "amount_base_raw" numeric NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, "vault_id" character varying, CONSTRAINT "PK_ed17b6e56f8b84d5a8f56d7e6bf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_fddfd84039fb3ac6270bd5e20f" ON "manager_withdraw" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_fea02801cb1c6c5b3577056491" ON "manager_withdraw" ("vault_address") `)
        await db.query(`CREATE INDEX "IDX_f13d9df2b990640dffe35e76fd" ON "manager_withdraw" ("borrower") `)
        await db.query(`CREATE INDEX "IDX_ae20c20dbc73c152f003b23fdd" ON "manager_withdraw" ("token") `)
        await db.query(`CREATE INDEX "IDX_cbbeaa0c0eb773d9699f2e34c4" ON "manager_withdraw" ("tx_hash") `)
        await db.query(`CREATE TABLE "manager_deposit" ("id" character varying NOT NULL, "vault_address" text NOT NULL, "borrower" text NOT NULL, "token" text NOT NULL, "amount_raw" numeric NOT NULL, "token_decimals" integer NOT NULL, "amount_base_raw" numeric NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, "vault_id" character varying, CONSTRAINT "PK_2be21f0dfa6cd601a8eb5caa9f4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_12abeab3607a7ce157a929292c" ON "manager_deposit" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_faec68388efd8012be91dc72ff" ON "manager_deposit" ("vault_address") `)
        await db.query(`CREATE INDEX "IDX_48e5fbd110017bedef3fc427ca" ON "manager_deposit" ("borrower") `)
        await db.query(`CREATE INDEX "IDX_78e7117374625a959796e84251" ON "manager_deposit" ("token") `)
        await db.query(`CREATE INDEX "IDX_7e5b288445fb962e8c4a74d6d3" ON "manager_deposit" ("tx_hash") `)
        await db.query(`CREATE TABLE "borrowed_asset_balance" ("id" character varying NOT NULL, "vault_address" text NOT NULL, "borrower" text NOT NULL, "token" text NOT NULL, "token_decimals" integer NOT NULL, "amount_raw" numeric NOT NULL, "amount_base_raw" numeric NOT NULL, "updated_at_ts" numeric NOT NULL, "last_tx_hash" text NOT NULL, "vault_id" character varying, CONSTRAINT "PK_e9ef1934ba95a621ae042e8d905" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_79bfac9057893f4c54362a3dab" ON "borrowed_asset_balance" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_8532da823adbb2eb62bb868003" ON "borrowed_asset_balance" ("vault_address") `)
        await db.query(`CREATE INDEX "IDX_3e345a9fc22215cf6eb61c5a2d" ON "borrowed_asset_balance" ("borrower") `)
        await db.query(`CREATE INDEX "IDX_cdb9f2580a976cbe172a1934f0" ON "borrowed_asset_balance" ("token") `)
        await db.query(`CREATE TABLE "expected_exchange_rate_cursor" ("id" character varying NOT NULL, "last_update_ts" integer NOT NULL, CONSTRAINT "PK_c5ca723905f8d5a2123a2298165" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "strategy_yield_state" ("id" character varying NOT NULL, "network" text NOT NULL, "kind" character varying(9) NOT NULL, "key" text NOT NULL, "last_day_start_ts" integer NOT NULL, "index_wad" numeric NOT NULL, "updated_at_ts" integer NOT NULL, CONSTRAINT "PK_8cca7c96547b682f8c7634bf0f3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8271afec97765bf8bd852bd247" ON "strategy_yield_state" ("network") `)
        await db.query(`CREATE INDEX "IDX_8e38ac8b388c2c86b9ff28c7b8" ON "strategy_yield_state" ("kind") `)
        await db.query(`CREATE INDEX "IDX_22d0aab04de91ed509c50a2cfb" ON "strategy_yield_state" ("key") `)
        await db.query(`CREATE TABLE "strategy_yield_snapshot" ("id" character varying NOT NULL, "network" text NOT NULL, "kind" character varying(9) NOT NULL, "key" text NOT NULL, "day_start_ts" integer NOT NULL, "index_wad" numeric NOT NULL, "updated_at_ts" integer NOT NULL, CONSTRAINT "PK_08b04b07f5594bcf9ef73cb410c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e6323e4aafc19d31c206fc3039" ON "strategy_yield_snapshot" ("network") `)
        await db.query(`CREATE INDEX "IDX_87e91a4cd8f6a4e3c1e1ba4c37" ON "strategy_yield_snapshot" ("kind") `)
        await db.query(`CREATE INDEX "IDX_faf034fb68691bb4c58ca0814d" ON "strategy_yield_snapshot" ("key") `)
        await db.query(`CREATE INDEX "IDX_9ab5418e2b3a45c697fce45e55" ON "strategy_yield_snapshot" ("day_start_ts") `)
        await db.query(`CREATE TABLE "strategy_position_snapshot" ("id" character varying NOT NULL, "strategy_addr" text NOT NULL, "last_read_ts_sec" integer NOT NULL, "value_base_raw" numeric NOT NULL, "principal_base_raw" numeric, "source" text NOT NULL, "block_height" numeric NOT NULL, "block_timestamp_sec" integer NOT NULL, "tx_hash" text, "vault_id" character varying, CONSTRAINT "PK_82cd478143027477327833d3074" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_aae201b7b2080a490d07546da2" ON "strategy_position_snapshot" ("vault_id") `)
        await db.query(`CREATE INDEX "IDX_47a62f9c5c114b11fe7a417e12" ON "strategy_position_snapshot" ("strategy_addr") `)
        await db.query(`CREATE INDEX "IDX_b0bf248ee391d40bd948ffafc5" ON "strategy_position_snapshot" ("last_read_ts_sec") `)
        await db.query(`CREATE TABLE "block_batch_audit" ("id" character varying NOT NULL, "network" character varying(16) NOT NULL, "first_height" numeric NOT NULL, "last_height" numeric NOT NULL, "count" integer NOT NULL, "expected_count" integer NOT NULL, "started_at" numeric NOT NULL, "finished_at" numeric NOT NULL, CONSTRAINT "PK_9ccd7a6bd1d1831ba4e92f55c41" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_112d366856e60eab09807859cc" ON "block_batch_audit" ("network") `)
        await db.query(`CREATE INDEX "IDX_186a36c610e62e6544a7cd8dff" ON "block_batch_audit" ("first_height") `)
        await db.query(`CREATE INDEX "IDX_25f5419b594f49935c6a4fe85c" ON "block_batch_audit" ("last_height") `)
        await db.query(`ALTER TABLE "port_vault" ADD CONSTRAINT "FK_af4e487a8df3021fcdbce98f085" FOREIGN KEY ("base_token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_withdrawal_request" ADD CONSTRAINT "FK_ffc5d7d8ae2d3710c768b4ee4b9" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_withdrawal_request" ADD CONSTRAINT "FK_e669b50286dda06958d2c860a97" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_withdrawal_request" ADD CONSTRAINT "FK_e4661991fc8d871c22a29fd3cb0" FOREIGN KEY ("want_token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_deposit" ADD CONSTRAINT "FK_f32f083592626a10515f34cb5ad" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_deposit" ADD CONSTRAINT "FK_f63dd6895d5c954fe797fda6743" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_deposit" ADD CONSTRAINT "FK_ce5906346ec55f7708ea2f06f3f" FOREIGN KEY ("asset_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nara_redemption_activity" ADD CONSTRAINT "FK_a9c29e022e8df6ea4b5db132507" FOREIGN KEY ("redemption_id") REFERENCES "nara_redemption"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nara_redemption" ADD CONSTRAINT "FK_1323be9f9ee12a82d8840060748" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_nav_update" ADD CONSTRAINT "FK_47f489d5d233c0aeae12d2f8d6e" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_vault_status_update" ADD CONSTRAINT "FK_4c9343dbb0386a2fd79a60a5be0" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_request_fulfilled" ADD CONSTRAINT "FK_69e031e6972e23e8fd9823e3187" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_request_fulfilled" ADD CONSTRAINT "FK_8f55ac51781c6ff117f55673c7e" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_request_fulfilled" ADD CONSTRAINT "FK_7724bff57c4be6c381352008835" FOREIGN KEY ("want_token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_vault_activity" ADD CONSTRAINT "FK_dd39c6dd9ddb312e0a164fb9744" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_vault_transaction_history" ADD CONSTRAINT "FK_368b5d2673663117cb85534a758" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_vault_transaction_history" ADD CONSTRAINT "FK_6c430ee33ebf67f6b6d58ddfa5e" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_vault_apy" ADD CONSTRAINT "FK_f957e82b58c244c4f23fdf2590d" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "port_vault_apy_chart" ADD CONSTRAINT "FK_ead1b71dee7261317832feb1eee" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "funds_diverted" ADD CONSTRAINT "FK_c5eaa6b419c6158d79befc5f381" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "funds_reverted" ADD CONSTRAINT "FK_50cb90c60da3d340d244b1033ad" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "expected_exchange_rate" ADD CONSTRAINT "FK_f05d1bb98338c38d52a9803864d" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "expected_exchange_rate_snapshot" ADD CONSTRAINT "FK_7d4893109abde7ce94552a1e22f" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "manager_withdraw" ADD CONSTRAINT "FK_fddfd84039fb3ac6270bd5e20f4" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "manager_deposit" ADD CONSTRAINT "FK_12abeab3607a7ce157a929292c7" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "borrowed_asset_balance" ADD CONSTRAINT "FK_79bfac9057893f4c54362a3dabc" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "strategy_position_snapshot" ADD CONSTRAINT "FK_aae201b7b2080a490d07546da20" FOREIGN KEY ("vault_id") REFERENCES "port_vault"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "token"`)
        await db.query(`DROP INDEX "public"."IDX_40a4dcc6b727285c6539aa1d1c"`)
        await db.query(`DROP INDEX "public"."IDX_b1c1e33dcc0f808971cf0540d8"`)
        await db.query(`DROP INDEX "public"."IDX_e31c0ee2b8847dc76f3646ecc7"`)
        await db.query(`DROP TABLE "port_vault"`)
        await db.query(`DROP INDEX "public"."IDX_981890e7e8876416d00d330b13"`)
        await db.query(`DROP INDEX "public"."IDX_af4e487a8df3021fcdbce98f08"`)
        await db.query(`DROP TABLE "port_withdrawal_request"`)
        await db.query(`DROP INDEX "public"."IDX_ffc5d7d8ae2d3710c768b4ee4b"`)
        await db.query(`DROP INDEX "public"."IDX_e669b50286dda06958d2c860a9"`)
        await db.query(`DROP INDEX "public"."IDX_68b6f1d4b96f2d84200cac48d1"`)
        await db.query(`DROP INDEX "public"."IDX_e4661991fc8d871c22a29fd3cb"`)
        await db.query(`DROP TABLE "port_deposit"`)
        await db.query(`DROP INDEX "public"."IDX_f32f083592626a10515f34cb5a"`)
        await db.query(`DROP INDEX "public"."IDX_f63dd6895d5c954fe797fda674"`)
        await db.query(`DROP INDEX "public"."IDX_ce5906346ec55f7708ea2f06f3"`)
        await db.query(`DROP TABLE "nara_redemption_activity"`)
        await db.query(`DROP INDEX "public"."IDX_a9c29e022e8df6ea4b5db13250"`)
        await db.query(`DROP INDEX "public"."IDX_fd4e1ddb2b0368ba16662243b4"`)
        await db.query(`DROP INDEX "public"."IDX_ac22e44a76a1ce576cc4975b22"`)
        await db.query(`DROP INDEX "public"."IDX_380f801a670e857ab75cec5bd6"`)
        await db.query(`DROP TABLE "nara_redemption"`)
        await db.query(`DROP INDEX "public"."IDX_1323be9f9ee12a82d884006074"`)
        await db.query(`DROP INDEX "public"."IDX_cc3976bd4ca46d3f94248749bd"`)
        await db.query(`DROP INDEX "public"."IDX_27a5f8bb0ac57cd1868e5dddd0"`)
        await db.query(`DROP TABLE "user"`)
        await db.query(`DROP INDEX "public"."IDX_3122b4b8709577da50e89b6898"`)
        await db.query(`DROP TABLE "nara_global_stats"`)
        await db.query(`DROP INDEX "public"."IDX_49add277f5c2a04994682fe6bc"`)
        await db.query(`DROP TABLE "nara_supply_chart_point"`)
        await db.query(`DROP INDEX "public"."IDX_1cfd9f5fb99a6c2c36c24c1de0"`)
        await db.query(`DROP INDEX "public"."IDX_b1fbcf17de84907b8550cb9d74"`)
        await db.query(`DROP TABLE "nara_tvl_chart_point"`)
        await db.query(`DROP INDEX "public"."IDX_e9a05a0bc52b6244ecd9c4e909"`)
        await db.query(`DROP INDEX "public"."IDX_cf3e74235a27cda9498071f39b"`)
        await db.query(`DROP INDEX "public"."IDX_2bad7d295eae01d163f98acf1f"`)
        await db.query(`DROP TABLE "nara_apy_chart_point"`)
        await db.query(`DROP INDEX "public"."IDX_7d48d7547ad17620d0adcdb0f4"`)
        await db.query(`DROP INDEX "public"."IDX_6c9dc0e906a792145f68a710e3"`)
        await db.query(`DROP TABLE "total_requested_amount"`)
        await db.query(`DROP INDEX "public"."IDX_39e056ef1c3652021a6ed6988b"`)
        await db.query(`DROP TABLE "port_global_stats"`)
        await db.query(`DROP INDEX "public"."IDX_d47d6e1f236c286246682d21e9"`)
        await db.query(`DROP TABLE "port_nav_update"`)
        await db.query(`DROP INDEX "public"."IDX_47f489d5d233c0aeae12d2f8d6"`)
        await db.query(`DROP TABLE "port_vault_status_update"`)
        await db.query(`DROP INDEX "public"."IDX_4c9343dbb0386a2fd79a60a5be"`)
        await db.query(`DROP TABLE "port_request_fulfilled"`)
        await db.query(`DROP INDEX "public"."IDX_69e031e6972e23e8fd9823e318"`)
        await db.query(`DROP INDEX "public"."IDX_8f55ac51781c6ff117f55673c7"`)
        await db.query(`DROP INDEX "public"."IDX_7724bff57c4be6c38135200883"`)
        await db.query(`DROP TABLE "port_vault_activity"`)
        await db.query(`DROP INDEX "public"."IDX_dd39c6dd9ddb312e0a164fb974"`)
        await db.query(`DROP TABLE "port_vault_transaction_history"`)
        await db.query(`DROP INDEX "public"."IDX_368b5d2673663117cb85534a75"`)
        await db.query(`DROP INDEX "public"."IDX_6c430ee33ebf67f6b6d58ddfa5"`)
        await db.query(`DROP TABLE "port_vault_apy"`)
        await db.query(`DROP INDEX "public"."IDX_f957e82b58c244c4f23fdf2590"`)
        await db.query(`DROP TABLE "port_vault_apy_chart"`)
        await db.query(`DROP INDEX "public"."IDX_ead1b71dee7261317832feb1ee"`)
        await db.query(`DROP TABLE "funds_diverted"`)
        await db.query(`DROP INDEX "public"."IDX_c5eaa6b419c6158d79befc5f38"`)
        await db.query(`DROP TABLE "funds_reverted"`)
        await db.query(`DROP INDEX "public"."IDX_50cb90c60da3d340d244b1033a"`)
        await db.query(`DROP TABLE "expected_exchange_rate"`)
        await db.query(`DROP INDEX "public"."IDX_f05d1bb98338c38d52a9803864"`)
        await db.query(`DROP TABLE "expected_exchange_rate_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_7d4893109abde7ce94552a1e22"`)
        await db.query(`DROP INDEX "public"."IDX_bddedd85f23f7d4251db99ba7d"`)
        await db.query(`DROP INDEX "public"."IDX_5dacf548b21859742ddf18b6b2"`)
        await db.query(`DROP INDEX "public"."IDX_4a29723480fdc001f735b1a0ed"`)
        await db.query(`DROP INDEX "public"."IDX_fb7ae07e1c46f9d74252682dec"`)
        await db.query(`DROP TABLE "manager_withdraw"`)
        await db.query(`DROP INDEX "public"."IDX_fddfd84039fb3ac6270bd5e20f"`)
        await db.query(`DROP INDEX "public"."IDX_fea02801cb1c6c5b3577056491"`)
        await db.query(`DROP INDEX "public"."IDX_f13d9df2b990640dffe35e76fd"`)
        await db.query(`DROP INDEX "public"."IDX_ae20c20dbc73c152f003b23fdd"`)
        await db.query(`DROP INDEX "public"."IDX_cbbeaa0c0eb773d9699f2e34c4"`)
        await db.query(`DROP TABLE "manager_deposit"`)
        await db.query(`DROP INDEX "public"."IDX_12abeab3607a7ce157a929292c"`)
        await db.query(`DROP INDEX "public"."IDX_faec68388efd8012be91dc72ff"`)
        await db.query(`DROP INDEX "public"."IDX_48e5fbd110017bedef3fc427ca"`)
        await db.query(`DROP INDEX "public"."IDX_78e7117374625a959796e84251"`)
        await db.query(`DROP INDEX "public"."IDX_7e5b288445fb962e8c4a74d6d3"`)
        await db.query(`DROP TABLE "borrowed_asset_balance"`)
        await db.query(`DROP INDEX "public"."IDX_79bfac9057893f4c54362a3dab"`)
        await db.query(`DROP INDEX "public"."IDX_8532da823adbb2eb62bb868003"`)
        await db.query(`DROP INDEX "public"."IDX_3e345a9fc22215cf6eb61c5a2d"`)
        await db.query(`DROP INDEX "public"."IDX_cdb9f2580a976cbe172a1934f0"`)
        await db.query(`DROP TABLE "expected_exchange_rate_cursor"`)
        await db.query(`DROP TABLE "strategy_yield_state"`)
        await db.query(`DROP INDEX "public"."IDX_8271afec97765bf8bd852bd247"`)
        await db.query(`DROP INDEX "public"."IDX_8e38ac8b388c2c86b9ff28c7b8"`)
        await db.query(`DROP INDEX "public"."IDX_22d0aab04de91ed509c50a2cfb"`)
        await db.query(`DROP TABLE "strategy_yield_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_e6323e4aafc19d31c206fc3039"`)
        await db.query(`DROP INDEX "public"."IDX_87e91a4cd8f6a4e3c1e1ba4c37"`)
        await db.query(`DROP INDEX "public"."IDX_faf034fb68691bb4c58ca0814d"`)
        await db.query(`DROP INDEX "public"."IDX_9ab5418e2b3a45c697fce45e55"`)
        await db.query(`DROP TABLE "strategy_position_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_aae201b7b2080a490d07546da2"`)
        await db.query(`DROP INDEX "public"."IDX_47a62f9c5c114b11fe7a417e12"`)
        await db.query(`DROP INDEX "public"."IDX_b0bf248ee391d40bd948ffafc5"`)
        await db.query(`DROP TABLE "block_batch_audit"`)
        await db.query(`DROP INDEX "public"."IDX_112d366856e60eab09807859cc"`)
        await db.query(`DROP INDEX "public"."IDX_186a36c610e62e6544a7cd8dff"`)
        await db.query(`DROP INDEX "public"."IDX_25f5419b594f49935c6a4fe85c"`)
        await db.query(`ALTER TABLE "port_vault" DROP CONSTRAINT "FK_af4e487a8df3021fcdbce98f085"`)
        await db.query(`ALTER TABLE "port_withdrawal_request" DROP CONSTRAINT "FK_ffc5d7d8ae2d3710c768b4ee4b9"`)
        await db.query(`ALTER TABLE "port_withdrawal_request" DROP CONSTRAINT "FK_e669b50286dda06958d2c860a97"`)
        await db.query(`ALTER TABLE "port_withdrawal_request" DROP CONSTRAINT "FK_e4661991fc8d871c22a29fd3cb0"`)
        await db.query(`ALTER TABLE "port_deposit" DROP CONSTRAINT "FK_f32f083592626a10515f34cb5ad"`)
        await db.query(`ALTER TABLE "port_deposit" DROP CONSTRAINT "FK_f63dd6895d5c954fe797fda6743"`)
        await db.query(`ALTER TABLE "port_deposit" DROP CONSTRAINT "FK_ce5906346ec55f7708ea2f06f3f"`)
        await db.query(`ALTER TABLE "nara_redemption_activity" DROP CONSTRAINT "FK_a9c29e022e8df6ea4b5db132507"`)
        await db.query(`ALTER TABLE "nara_redemption" DROP CONSTRAINT "FK_1323be9f9ee12a82d8840060748"`)
        await db.query(`ALTER TABLE "port_nav_update" DROP CONSTRAINT "FK_47f489d5d233c0aeae12d2f8d6e"`)
        await db.query(`ALTER TABLE "port_vault_status_update" DROP CONSTRAINT "FK_4c9343dbb0386a2fd79a60a5be0"`)
        await db.query(`ALTER TABLE "port_request_fulfilled" DROP CONSTRAINT "FK_69e031e6972e23e8fd9823e3187"`)
        await db.query(`ALTER TABLE "port_request_fulfilled" DROP CONSTRAINT "FK_8f55ac51781c6ff117f55673c7e"`)
        await db.query(`ALTER TABLE "port_request_fulfilled" DROP CONSTRAINT "FK_7724bff57c4be6c381352008835"`)
        await db.query(`ALTER TABLE "port_vault_activity" DROP CONSTRAINT "FK_dd39c6dd9ddb312e0a164fb9744"`)
        await db.query(`ALTER TABLE "port_vault_transaction_history" DROP CONSTRAINT "FK_368b5d2673663117cb85534a758"`)
        await db.query(`ALTER TABLE "port_vault_transaction_history" DROP CONSTRAINT "FK_6c430ee33ebf67f6b6d58ddfa5e"`)
        await db.query(`ALTER TABLE "port_vault_apy" DROP CONSTRAINT "FK_f957e82b58c244c4f23fdf2590d"`)
        await db.query(`ALTER TABLE "port_vault_apy_chart" DROP CONSTRAINT "FK_ead1b71dee7261317832feb1eee"`)
        await db.query(`ALTER TABLE "funds_diverted" DROP CONSTRAINT "FK_c5eaa6b419c6158d79befc5f381"`)
        await db.query(`ALTER TABLE "funds_reverted" DROP CONSTRAINT "FK_50cb90c60da3d340d244b1033ad"`)
        await db.query(`ALTER TABLE "expected_exchange_rate" DROP CONSTRAINT "FK_f05d1bb98338c38d52a9803864d"`)
        await db.query(`ALTER TABLE "expected_exchange_rate_snapshot" DROP CONSTRAINT "FK_7d4893109abde7ce94552a1e22f"`)
        await db.query(`ALTER TABLE "manager_withdraw" DROP CONSTRAINT "FK_fddfd84039fb3ac6270bd5e20f4"`)
        await db.query(`ALTER TABLE "manager_deposit" DROP CONSTRAINT "FK_12abeab3607a7ce157a929292c7"`)
        await db.query(`ALTER TABLE "borrowed_asset_balance" DROP CONSTRAINT "FK_79bfac9057893f4c54362a3dabc"`)
        await db.query(`ALTER TABLE "strategy_position_snapshot" DROP CONSTRAINT "FK_aae201b7b2080a490d07546da20"`)
    }
}
